"""fix sync

Revision ID: fe6f5488fb10
Revises: 202606120006
Create Date: 2026-06-19 14:46:12.153777
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fe6f5488fb10'
down_revision: Union[str, None] = '202606120006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_addresses_user_default', 'addresses', ['user_id', 'is_default'], unique=False)
    op.add_column('audit_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs')
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_constraint('audit_logs_actor_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'actor_user_id')
    op.create_index('ix_bonus_transactions_fifo_lookup', 'bonus_transactions', ['user_id', 'restaurant_id', 'type', 'expires_at', 'created_at'], unique=False)
    op.create_index('ix_bonus_transactions_order_type', 'bonus_transactions', ['order_id', 'type'], unique=False)
    op.add_column('campaigns', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('campaigns', sa.Column('image_url', sa.String(length=2048), nullable=True))
    op.add_column('campaigns', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaigns', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_campaigns_created_by_user_id'), 'campaigns', ['created_by_user_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('campaigns', 'ends_at')
    op.drop_column('campaigns', 'starts_at')
    op.drop_column('campaigns', 'message')
    op.create_unique_constraint('uq_delivery_orders_order_id', 'delivery_orders', ['order_id'])
    op.create_index('ix_user_activities_last_visit_at', 'user_activities', ['last_visit_at'], unique=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_index(op.f('ix_users_created_by_user_id'), 'users', ['created_by_user_id'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_created_by_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_column('users', 'created_by_user_id')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_active')
    op.drop_index('ix_user_activities_last_visit_at', table_name='user_activities')
    op.drop_constraint('uq_delivery_orders_order_id', 'delivery_orders', type_='unique')
    op.add_column('campaigns', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('starts_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('ends_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_created_by_user_id'), table_name='campaigns')
    op.drop_column('campaigns', 'updated_at')
    op.drop_column('campaigns', 'created_by_user_id')
    op.drop_column('campaigns', 'end_date')
    op.drop_column('campaigns', 'start_date')
    op.drop_column('campaigns', 'image_url')
    op.drop_column('campaigns', 'description')
    op.drop_index('ix_bonus_transactions_order_type', table_name='bonus_transactions')
    op.drop_index('ix_bonus_transactions_fifo_lookup', table_name='bonus_transactions')
    op.add_column('audit_logs', sa.Column('actor_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_actor_user_id_fkey', 'audit_logs', 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False)
    op.drop_column('audit_logs', 'user_id')
    op.drop_index('ix_addresses_user_default', table_name='addresses')
    # ### end Alembic commands ###
